baseURL = "/"
languageCode = "en"                                      # website language
defaultContentLanguage = "en"                            # [en, zh, ...] determines which i18n file to use
title = "Final SDS348 Project-My Website"                                   # website title
theme = "LoveIt"
enableGitInfo = false                                    # whether to use git commit log to generate lastmod record
hasCJKLanguage = false                                   # whether to include chinese/japanese/korean
paginate = 12                                            # default amount of posts in each pages
enableEmoji = true                                       # whether to use emoji code
enableRobotsTXT = true                                   # whether to use robots.txt
googleAnalytics = ""                                     # [UA-XXXXXXXX-X] google analytics code
disqusShortname = "dillonzq"                             # Disqus shortname to use Disqus in posts
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
                                                         # copyright description used only for seo schema

                                                      #### Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
pygmentsOptions = "linenos=table"
pygmentsCodefences = true
pygmentsUseClasses = true
pygmentsCodefencesGuessSyntax = true

staticDir = ["static", "../assets/others"]               # static directories

[author]                                              #### Author Info
  name = "Tu Hoang"

[sitemap]                                             #### Sitemap Info
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[Permalinks]                                          #### Permalinks Info (https://gohugo.io/content-management/urls/#permalinks)
  posts = ":year/:month/:filename"

[menu]
  [[menu.main]]
  identifier = "resume"
  name = "Resume"
  url= "static"
  weight = 1
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "blog"
    weight = 1

  [[menu.main]]
    identifier = "Project1"
    name = "Project1"
    url = "Project1"
    weight = 3
  
  [[menu.main]]
  identifier = "Project2"
  name ="Project2"
  url= "Project2"
  weight = 3
  

  [[menu.main]]
    identifier = "About Me"
    name = "About Me"
    url = "about"
    weight = 4
    
[params]
  version = "5.x"                                        # LoveIt theme version
  description = "LoveIt Theme Demo"                      # site description
  keywords = ["XXXX", "Theme", "Hugo"]                   # site keywords

                                                      #### Home Page Info
  home_mode = "post"                                     # [post, other] home mode
  home_paginate = 6                                      # special amount of posts in each home post page
  avatar = "/IMG_7574.JPG"                           # URL of avatar shown in home page
  subtitle = "The greatest glory in living lies not in never falling, but in rising every time we fall.-Nelson Mandela"  # subtitle shown in home page

  socialShare = true                                     # whether to show social share links in post page

                                                      #### Footer CopyRight Info
  since = 2018                                           # Site creation time
  icp = ''                                               # ICP info only in China (HTML format is allowed)
  license=                                              # license info (HTML format is allowed)
  gitRepo = ""                                           # public git repo url to link lastmod git commit only then enableGitInfo is true

  linkToMarkdown = true                                  # whether to show link to Raw Markdown content of the post

                                                      #### site verification code for Google/Bing/Yandex/Pinterest/Baidu
  google_verification = ""
  bing_verification = ""
  yandex_verification = ""
  pinterest_verification = ""
  baidu_verification = ""

  [params.cdn]                                       #### CSS and JS Files CDN
    fontawesome_free_css = ''                           # for example '<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.10.1/css/all.min.css" integrity="sha256-fdcFNFiBMrNfWL6OcAGQz6jDgNTRxnrLEd4vJYFWScE=" crossorigin="anonymous">'
    animate_css = ''
    gitalk_css = ''
    gitalk_js = ''
    valine_js = ''
    jquery_js = ''
    lazysizes_js = ''
    smooth_scroll_js = ''
    katex_css = ''
    katex_js = ''
    katex_auto_render_js = ''
    mermaid_js = ''
    echarts_js = ''
    echarts_macarons_js = ''
    typeit_js = ''
    jquery_countdown_js = ''
    aplayer_css = ''
    aplayer_js = ''
    meting_js = ''

  [params.gravatar]                                      # Gravatar Info for preferred avatar in home page
    email = ""

  [params.social]                                        # Social Info in home page
    GitHub = "tuhoang355"
    Email = "tuhoang355@utexas.edu"
    Facebook = "https://www.facebook.com/tu.hoang.39395"
    Snapchat = "@awesomero.dos"
    
  [params.publisher]                                     # Publisher Info just for SEO
    name = "XXXX"
    [params.publisher.logo]
      url = "logo.png"
      width = 127
      height = 40

  [params.logo]                                          # Website Log Info just for SEO
    url = "logo.png"
    width = 127
    height = 40

  [params.image]                                         # Website Image Info just for SEO
    url = "cover.png"
    width = 1000
    height = 1600

  [params.gitalk]                                        # Gittalk Comment Config (https://github.com/gitalk/gitalk)
    owner = ""
    repo = ""
    clientId = ""
    clientSecret = ""

  [params.valine]                                        # Valine Comment Config (https://github.com/xCss/Valine)
    enable = false
    appId = ""
    appKey = ""
    notify = false
    verify = true
    avatar = "mp"
    placeholder = "Your comment ..."
    visitor = true
    recordIP = true

[privacy]                                             #### Privacy Info (https://gohugo.io/about/hugo-and-gdpr/)
  [privacy.googleAnalytics]
    anonymizeIP = true

  [privacy.youtube]
    privacyEnhanced = true

[mediaTypes]                                          #### Options to make hugo output .md files.
  [mediaTypes."text/plain"]
    suffixes = ["md"]

[outputFormats.MarkDown]                              #### Options to make hugo output .md files.
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

[outputs]                                             #### Options to make hugo output .md files.
  home = ["HTML", "RSS"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML"]
